<a href="https://colab.research.google.com/github/heewon04/2025_DM/blob/main/%EC%9D%B4%EC%82%B0%EC%88%98_4%EC%A3%BC%EC%B0%A8_%EA%B4%80%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) 이항 관계 예제

In [1]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

A={1,2,3}
B={2,3,4}
# A에서 B로 가는 이항 관계 R
R={(1,2),(2,3),(3,2),(3,4)}

print("관계 R:",R)



관계 R: {(2, 3), (3, 2), (1, 2), (3, 4)}


2) 관계 행렬 표현

In [3]:
A_list=sorted(A)
B_list=sorted(B)

relation_matrix=np.zeros((len(A_list), len(B_list)), dtype=int)

for i, a in enumerate(A_list):
  for j, b in enumerate(B_list):
    if (a,b) in R:
      relation_matrix[i,j]=1

print("관계 행렬 (row: A, columns: B):")
print(relation_matrix)

관계 행렬 (row: A, columns: B):
[[1 0 0]
 [0 1 0]
 [1 0 1]]


3) 합성 관계 예제

In [4]:
# R: A -> B
# S: B -> C
C={'x','y'}
S={(2,'x'),(3,'y'),(4,'x')}

# 합성 관계 RºS
composed_relation=set()

for (a,b1) in R:
  for(b2,c) in S:
    if b1==b2:
      composed_relation.add((a,c))

print("\n합성 관계 RºS:",composed_relation)


합성 관계 RºS: {(3, 'x'), (1, 'x'), (2, 'y')}
